services:
  - type: web
    name: parking-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URI
        sync: false
      - key: SECRET_JWT_CODE
        sync: false
      - key: SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false 